# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_machinelearningdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
